language: rust

rust:
  - stable

script:
  - cargo install --vers "0.0.22" --no-default-features --features output mdbook
  - mdbook build

deploy:
  provider: pages
  local_dir: book
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
