language: rust

rust:
  - stable

script:
  - cargo install mdbook --vers "^0.3" --no-default-features --features output
  - mdbook build

deploy:
  provider: pages
  local_dir: book
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
