[book]
title = "Die Programmiersprache Rust"
author = "Steve Klabnik und Carol Nichols, unter Mitarbeit der Rust-Gemeinschaft"
description = "Eine deutsche Gemeinschafts-Übersetzung des offiziellen Rust-Buchs."
language = "de"

[output.html]
additional-css = ["theme/ferris.css", "theme/2018-edition.css"]
additional-js = ["theme/ferris.js"]
git-repository-url = "https://github.com/rust-lang-de/rustbook-de"
